const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  const page = await browser.newPage({viewport: {width: 1280, height: 800}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  const card = page.locator('.q-card').first();
  assert.equal(await page.locator('.q-card').count(), 54);
  assert.equal(await page.locator('.hint').count(), 0);
  assert.equal(await card.getByText('编辑 Hint', {exact:true}).count(), 0);
  await card.getByText('显示 Hint', {exact:true}).click();
  assert.equal(await card.locator('.hint li').count(), 3);
  assert.equal(await card.locator('.hint button').innerText(), '编辑 Hint');
  await card.getByText('隐藏 Hint', {exact:true}).click();
  assert.equal(await card.locator('.hint').count(), 0);
  await card.getByText('显示 Hint', {exact:true}).click();
  await card.getByText('编辑 Hint', {exact:true}).click();
  await page.locator('textarea').first().fill('自定义浅层提示 <test>');
  await page.click('#addHint');
  await page.locator('textarea').last().fill('第四条提示');
  await page.getByText('保存 Hint', {exact:true}).click();
  assert.equal(await card.locator('.hint li').count(), 4);
  assert.equal(await card.locator('.hint li').first().innerText(), '自定义浅层提示 <test>');
  await page.reload();
  assert.equal(await page.locator('.hint').count(), 0);
  await card.getByText('显示 Hint', {exact:true}).click();
  assert.equal(await card.locator('.hint li').count(), 4);
  await card.getByText('编辑 Hint', {exact:true}).click();
  await page.locator('textarea').first().fill('取消的内容');
  await page.click('#cancelHints');
  assert.equal(await card.locator('.hint li').first().innerText(), '自定义浅层提示 <test>');
  await page.click('#modeToggle');
  assert.equal(await page.locator('.hint').count(), 0);
  assert.equal(await card.locator('.q-actions button').count(), 1);
  page.once('dialog', d => d.dismiss());
  await card.getByText('显示 Hint', {exact:true}).click();
  assert.equal(await card.locator('.hint').count(), 0);
  for (const n of [1,2,3,4,1]) {
    page.once('dialog', d => d.accept());
    await card.getByText('显示 Hint', {exact:true}).click();
    assert.equal(await card.locator('.hint h4').innerText(), `Hint ${n} / 4`);
  }
  assert.equal(await card.locator('.hint p').innerText(), '自定义浅层提示 <test>');
  const second = page.locator('.q-card').nth(1);
  await second.locator('[data-letter="A"]').click();
  assert.equal(await second.locator('.incorrect.option').count(), 1);
  assert.equal(await card.locator('.incorrect.option').count(), 0);
  await second.locator('[data-letter="E"]').click();
  assert.equal(await second.locator('.correct.option').count(), 1);
  await page.selectOption('#yearSel','2002');
  assert.equal(await page.locator('.q-card').count(),30);
  assert.match(await card.locator('.q-title').innerText(), /Grade 5-6/);
  await page.selectOption('#viewSel','single');
  assert.equal(await page.locator('.q-card').count(),1);
  await page.selectOption('#viewSel','list');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await page.locator('#app').hover(); await page.mouse.wheel(0,600); await page.waitForTimeout(200);
  assert.ok(await page.locator('#app').evaluate(el => el.scrollTop > 0));
  assert.equal(await page.locator('.q-card').count(),30);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: multi-question browsing, teaching hints, edit/save/reload/cancel, practice hint cycle, answer isolation, filters, mobile scrolling.');
})().catch(e => {console.error(e);process.exitCode=1;});
