const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const {pathToFileURL} = require('node:url');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless: true, channel: 'msedge'});
  const page = await browser.newPage({viewport: {width: 1280, height: 800}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(pathToFileURL(path.resolve('index.html')).href);
  assert.equal(await page.locator('.q-card').count(), 1);
  assert.match(await page.locator('.q-title').innerText(), /1999 · Grade 3-4/);
  await page.click('#btnToggleAns');
  assert.equal(await page.locator('.option.correct').count(), 1);
  await page.click('#modeToggle');
  assert.equal(await page.locator('.option.correct').count(), 0);
  assert.equal(await page.locator('.q-actions button').count(), 1);
  assert.equal(await page.locator('.tip,.solution,.diagram,.methods').count(), 0);
  assert.equal(await page.locator('#btnToggleAns').isVisible(), false);
  await page.click('[data-letter="A"]');
  assert.equal(await page.locator('.incorrect.option').count(), 1);
  assert.equal(await page.locator('.correct.option').count(), 0);
  await page.click('[data-letter="C"]');
  assert.equal(await page.locator('.correct.option').count(), 1);
  assert.equal(await page.locator('.incorrect.option').count(), 0);
  page.once('dialog', d => d.dismiss());
  await page.click('.q-actions button');
  assert.equal(await page.locator('.hint').count(), 0);
  for (const n of [1,2,3,1]) {
    page.once('dialog', d => d.accept());
    await page.click('.q-actions button');
    assert.equal(await page.locator('.hint h4').innerText(), `Hint ${n} / 3`);
  }
  await page.click('#nextQuestion');
  assert.equal(await page.locator('.hint').count(), 0);
  assert.match(await page.locator('.q-title').innerText(), /Q2$/);
  await page.click('#prevQuestion');
  assert.equal(await page.locator('.hint h4').innerText(), 'Hint 1 / 3');
  assert.equal(await page.locator('.correct.option').count(), 1);
  await page.selectOption('#yearSel', '2002');
  assert.match(await page.locator('.q-title').innerText(), /Grade 5-6/);
  assert.match(await page.locator('#progress').innerText(), /1 \/ 30/);
  await page.waitForTimeout(700);
  await page.locator('#app').hover();
  await page.mouse.wheel(0, 200);
  await page.waitForTimeout(100);
  assert.match(await page.locator('.q-title').innerText(), /Q2$/);
  await page.click('#modeToggle');
  await page.selectOption('#viewSel', 'answers');
  assert.equal(await page.locator('.ans-cell').count(), 30);
  await page.click('#modeToggle');
  assert.equal(await page.locator('.ans-cell').count(), 0);
  assert.equal(await page.locator('.q-card').count(), 1);
  await page.fill('#search', 'zzzz-no-match');
  assert.equal(await page.locator('.empty').count(), 1);
  await page.fill('#search', '');
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  // A long question must scroll within itself before navigation is possible.
  const before = await page.locator('.q-title').innerText();
  await page.locator('#app').hover();
  await page.mouse.wheel(0, 60);
  await page.waitForTimeout(150);
  assert.equal(await page.locator('.q-title').innerText(), before);
  assert.ok(await page.locator('#app').evaluate(el => el.scrollTop > 0));
  if (process.env.SAVE_SCREENSHOTS) await page.screenshot({path:'verification-mobile.png'});
  await page.setViewportSize({width:1280,height:800});
  if (process.env.SAVE_SCREENSHOTS) await page.screenshot({path:'verification-desktop.png'});
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: grade labels, one-card browsing, wheel navigation, practice isolation, answer feedback, hint confirmation/cycle/persistence, filters, mobile overflow; no browser errors.');
})().catch(e => {console.error(e);process.exitCode=1;});
